### ISSUE TITLE
Have you done some benchmark ?

### ISSUE THREAD

**Issue by vasilvestre** [royalphp/frankenphp-sylius#1]
Is there a way to share a benchmark or the typical sylius-standard and this fork ?

If you have some obviously, otherwise I will try myself. Thank you !

**Comment by royalphp** [comment]
Hello @vasilvestre

Our starting point was to create a workable project that could be used here and now, so we expected to get as much performance as [here](https://github.com/dunglas/frankenphp-demo/tree/main/benchmark).

Also, we have plans to make a demo project based on this template, where there will be a specific benchmark in the combination of FrankenPHP and Sylius.

**Comment by vasilvestre** [comment]
> Hello @vasilvestre
> 
> Our starting point was to create a workable project that could be used here and now, so we expected to get as much performance as [here](https://github.com/dunglas/frankenphp-demo/tree/main/benchmark).
> 
> Also, we have plans to make a demo project based on this template, where there will be a specific benchmark in the combination of FrankenPHP and Sylius.

An impressive advantage of Frankenphp is that the more you rely on container the better the performance gain. You may get way better performance improvement :)

Thank you !

**Comment by vasilvestre** [comment]
This may not be perfect but here's my result :
 - opcache
 - prod
 - preload
 - PHP 8.3
 - no fpm tuning
 - no nginx tuning
 - 500 requests, 30 concurrent on a 15 threads laptop
 - sample data loaded

`ab -n 500 -c 30 http://localhost/en_US/`

## Fankenphp

```
Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        2    6   4.1      4      24
Processing:    49  104  11.5    105     146
Waiting:       31  103  11.5    104     136
Total:         52  110  11.9    110     151

Percentage of the requests served within a certain time (ms)
  50%    110
  66%    115
  75%    117
  80%    119
  90%    124
  95%    129
  98%    137
  99%    138
 100%    151 (longest request)
```

## Nginx FPM

```
Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.1      0       1
Processing:    49  237  40.6    232     419
Waiting:       49  237  40.7    232     419
Total:         50  237  40.6    232     419

Percentage of the requests served within a certain time (ms)
  50%    232
  66%    239
  75%    251
  80%    260
  90%    270
  95%    315
  98%    356
  99%    402
 100%    419 (longest request)
```

**Comment by royalphp** [comment]
The Sylius team did their performance and speed tests, you can view the test results here: https://sylius.com/blog/ecosystem/month-of-sylius-august-2024/#frankenphp
