### ISSUE TITLE
Error while building for production

### ISSUE THREAD

**Issue by vasilvestre** [royalphp/frankenphp-sylius#2]
The make command runs well until this :

```
You can now open your store at the following path under the website root: /
make[2]: Leaving directory '/root/projects/frankenphp-sylius'
make[1]: Leaving directory '/root/projects/frankenphp-sylius'
make build_assets
make[1]: Entering directory '/root/projects/frankenphp-sylius'
docker run --rm -v $(PWD):/app -w /app node:lts-alpine sh -c 'npm ci; npm run build'
/bin/sh: 1: PWD: not found
docker: invalid spec: :/app: empty section between colons.
See 'docker run --help'.
make[1]: *** [Makefile:96: build_assets] Error 125
make[1]: Leaving directory '/root/projects/frankenphp-sylius'
make: *** [Makefile:85: setup] Error 2
```

It seems reload to `build_assets`, $$(PWD) seems to be the error

**Comment by royalphp** [comment]
What environment did you run the Makefile commands in?

**Comment by vasilvestre** [comment]
Linux, the fix is pretty easy. I'm pretty sure it is a syntax issue :

```
docker run --rm -v $$(PWD):/app -w /app node:lts-alpine sh -c 'npm ci; npm run build'
```

**Comment by royalphp** [comment]
You probably ran this command from within the container itself.

**Comment by vasilvestre** [comment]
> You probably ran this command from within the container itself.

vsilvestre@pop-os:~/projects/perso/frankenphp-sylius$ make build_assets PROJECT_MODE=prod
docker run --rm -v $(PWD):/app -w /app node:lts-alpine sh -c 'npm ci; npm run build'
/bin/sh: 1: PWD: not found
docker: invalid spec: :/app: empty section between colons.
See 'docker run --help'.
make: *** [Makefile:96 : build_assets] Erreur 125

If I change the Makefile line 96, the command runs great
```diff
- 	docker run --rm -v $$(PWD):/app -w /app node:lts-alpine sh -c 'npm ci; npm run build'
+ 	docker run --rm -v $(PWD):/app -w /app node:lts-alpine sh -c 'npm ci; npm run build'
```

**Comment by royalphp** [comment]
Your solution works because $(PWD) is recognized as a variable, and if no such variable is specified, the default command will be executed. You can check it as follows: `make build_assets PROJECT_MODE=prod PWD=none`

We have defined another construct that should also return the same value in any environment, hopefully that will solve this problem.
