### ISSUE TITLE
Blank page when loading prod

### ISSUE THREAD

**Issue by vasilvestre** [royalphp/frankenphp-sylius#3]
The quick setup with the command :

`make setup PROJECT_MODE=prod`

Display a blank page, both on Windows WSL and Debian. I have fixed the makefile error for assets (see my other issue) and nothing is shown.

`Could not find the entrypoints file from Webpack`

**Comment by royalphp** [comment]
This issue is caused by the following issue: https://github.com/royalphp/frankenphp-sylius/issues/2
